#!/usr/bin/env php
<?php

use Morilog\BijectiveShortener\Console\Shortener;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}


$app = new Application();

$app->add(new Shortener());
$app->setDefaultCommand('shorten', true);
$app->run();
